service: sls-appSync-backend
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-2

plugins:
  - serverless-appsync-plugin

appSync:
  name: learningAppSyncAPI

  logging:
    level: ALL

  authentication:
    type: AMAZON_COGNITO_USER_POOLS
    config:
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool

  dataSources:
    booksTable:
      type: AMAZON_DYNAMODB
      config:
        tableName: !Ref booksTable
  
  resolvers:
    Query.getBookById:
      functions:
        - dataSource: booksTable
          code: resolvers/Query.getBookById.js
          

    Mutation.createBook:
      functions:
        - dataSource: booksTable
          code: resolvers/Mutation.createBook.js
resources:
  Resources: ${file(./resources.yml)}
